In [25]:
import numpy as np

In [26]:
#Task 1 — Creating Arrays
arr_1D = np.arange(1,11)
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
arr_zero = np.zeros((4,4))
arr_one = np.ones((2,5))

#Display the array
print(arr_1D)
print(arr_1D)
print(arr_zero)
print(arr_one)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
#Task 2 — Array Properties


shape = arr_2D.shape
size = arr_2D.size
type = arr_2D.dtype
dims = arr_2D.ndim
print(shape)
print(size)
print(type)
print(dims)

(3, 3)
9
int64
2


In [28]:
#Task 3 — Indexing

indx_arr = np.array([10,20,30,40,50,60])
first = indx_arr[0]
second = indx_arr[1]
third = indx_arr[2]
greater_then_30 = indx_arr[indx_arr > 30] 
print(first)
print(second)
print(third)
print(greater_then_30)

10
20
30
[40 50 60]


In [29]:
#Task 4 — Slicing
slice_1_to_4 = indx_arr[1:5]
reversed_arr = indx_arr[::-1]
alternate = indx_arr[::2]

#Display
print(f"slice_1_to_4 = {slice_1_to_4}")
print(f"reversed_arr = {reversed_arr}")
print(f"alternate = {alternate}")

#4. Create a 3×3 matrix and:
mat = np.arange(1,10).reshape(3,3)
first_row = mat[0,:]
second_column = mat[:, 1]
last_two_row = mat[1:,:]

#Display
print(f"first_row = {first_row}")
print(f"second_column = {second_column}")
print(f"last_two_row = {last_two_row}")

slice_1_to_4 = [20 30 40 50]
reversed_arr = [60 50 40 30 20 10]
alternate = [10 30 50]
first_row = [1 2 3]
second_column = [2 5 8]
last_two_row = [[4 5 6]
 [7 8 9]]


In [30]:
#Task 5 — Vectorization
vec_arr = np.array([1,2,3,4,5])
mul_5 = vec_arr * 5
add_10 = vec_arr + 10
mul_2 = vec_arr **2
print(f"mul_5 = {mul_5}")
print(f"add_10 = {add_10}")
print(f"mul_2 = {mul_2}")

mul_5 = [ 5 10 15 20 25]
add_10 = [11 12 13 14 15]
mul_2 = [ 1  4  9 16 25]


In [31]:
#Task 6 — Broadcasting
b_arr = np.array([[1,2,3],
                  [4,5,6]])
added_10 = b_arr+10,
multiply_2 = b_arr * 2
print(f"added_10 = {added_10}")
print(f"multiply_2 = {multiply_2}")

added_10 = (array([[11, 12, 13],
       [14, 15, 16]]),)
multiply_2 = [[ 2  4  6]
 [ 8 10 12]]


In [32]:
#Task 7 — Matrix Addition and Subtraction
mat_A = np.array([[1,2],[3,4]])
mat_B = np.array([[5,6],[7,8]])

add_mat = mat_A + mat_B
sub_mat = mat_A - mat_B

#display result
print(f" add_mat = {add_mat}")
print(f" sub_mat = {sub_mat}")

 add_mat = [[ 6  8]
 [10 12]]
 sub_mat = [[-4 -4]
 [-4 -4]]


In [33]:
#Task 8 — Matrix Multiplication

dot_product = np.dot(mat_A, mat_B)
transpose_mat_A =  mat_A.T
transpose_mat_B =  mat_B.T
print(f"dot_product = {dot_product}")
print(f"transpose_mat_A = {transpose_mat_A}")
print(f"transpose_mat_B = {transpose_mat_B}")

dot_product = [[19 22]
 [43 50]]
transpose_mat_A = [[1 3]
 [2 4]]
transpose_mat_B = [[5 7]
 [6 8]]


In [34]:
#Task 9 — Random Arrays

rand_int = np.random.randint(1,101, size = (4,4))
rand_dec = np.random.rand(3,3)
maximum_value = rand_int.max()
minimum_value = rand_int.min()
average_value = rand_int.mean()

#Dispaly

print(f"rand_dec = {rand_dec}")
print(f"maximum_value = {maximum_value}")
print(f"minimum_value = {minimum_value}")

rand_dec = [[0.97132917 0.34561911 0.27984223]
 [0.4196061  0.48402687 0.42264296]
 [0.89806634 0.66007607 0.87084376]]
maximum_value = 96
minimum_value = 1


In [35]:
#Task 10 — Student Marks Analysis

marks = np.array([85, 42, 90, 78, 55, 30, 88, 92, 49, 65])
avg_m,high_m,low_m = marks.mean(),marks.max(),marks.min()
above_80 = np.sum(marks > 80)
failed = marks[marks<50]

#Display

print(above_80)
print(failed)

4
[42 30 49]


In [36]:
# Task 11: Image Pixel Simulation

pixels = np.random.randint(0, 256, (5, 5))
brightest = pixels.max()
darkest = pixels.min()

#display
print(f"brightest = {brightest}")
print(f"darkest = {darkest}")

brightest = 213
darkest = 1


In [37]:
# Task 12: Data Normalization

data = np.array([100, 200, 300, 400, 500])
normalized = (data - data.min()) / (data.max() - data.min())

#Display
print(f"Data = {data}")
print(f"normalized =  {normalized}")

Data = [100 200 300 400 500]
normalized =  [0.   0.25 0.5  0.75 1.  ]


In [38]:
#Task 13 — Mini AI Dataset Task

# Columns: Age, Salary, Purchased
dataset = [
    [25, 50000, 0],
    [35, 75000, 1],
    [45, 120000, 1],
    [20, 25000, 0]
]

np_data = np.array(dataset)
features = np_data[:, :2]  
labels = np_data[:, 2]     
avg_salary = np_data[:, 1].mean()
max_age = np_data[:, 0].max()
dataset_shape = np_data.shape

#Display

print(f"features = {features}")
print(f"labels = {labels}")
print(f"avg_salary = {avg_salary}")
print(f"max_age = {max_age}")
print(f"dataset_shape = {dataset_shape}")

features = [[    25  50000]
 [    35  75000]
 [    45 120000]
 [    20  25000]]
labels = [0 1 1 0]
avg_salary = 67500.0
max_age = 45
dataset_shape = (4, 3)
